### ISSUE TITLE
Sanitizing "<u />" tags does not follow browser behaviour and causes noticeable performance penalties

### ISSUE THREAD

**Issue by zhajiang** [OWASP/java-html-sanitizer#116]
`<u />` is a non-void self-closing tag, which is invalid based on HTML5, but it's a test case from reality.  Attaching the test case.
[test.html.zip](https://github.com/OWASP/java-html-sanitizer/files/1098818/test.html.zip)

Run the test case from chrome browser, it generates around 1219 pairs of `<u></u>.`
However, java-html-sanitizer generates about 13001 pairs of `<u></u>` after sanitizing the file. There was a very noticeable delay of layout and rendering this sanitized file especially on mobile devices.

Expected behaviour:
It should follow browser behaviour while sanitizing this file without generating a large number of `<u></u>` elements and causing the performance penalties.

**Comment by Shazrina1994** [comment]
hlooo i want to get involve in this open source project. please help me

**Comment by jmanico** [comment]
Start by reviewing all the code and current bugs. Where do you want to
start helping? We love patches!

Aloha,

Jim

**Comment by mikesamuel** [comment]
I'm not going to download and unzip attachments from people I don't know onto my local machine.

Please put testcases in the bug text using an [HTML code section](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) like

<pre>```html
Your HTML goes here
```</pre>
