### ISSUE TITLE
Allow for urls using tel:

### ISSUE THREAD

**Issue by anthony-dandrea** [OWASP/java-html-sanitizer#118]
We account for `mailto:` but not html5's `tel:` functionality to call a number on click.

https://github.com/OWASP/java-html-sanitizer/blob/34425c15adb7bd32609cefc01e8f8d4534a3cf34/src/main/java/org/owasp/html/examples/EbayPolicyExample.java

**Comment by mikesamuel** [comment]
You can allow `tel:` URLs via [`allowUrlProtocols`](https://rawgit.com/OWASP/java-html-sanitizer/master/distrib/javadoc/org/owasp/html/HtmlPolicyBuilder.html#allowUrlProtocols)
