### ISSUE TITLE
Open ended dependencies 

### ISSUE THREAD

**Issue by sambekar** [OWASP/java-html-sanitizer#130]
It is important to have version boundaries defined in order to ensure compatibility and build integrity from quality perspective.
Hence I would like the the compile time dependencies for owasp java-html-sanitizer to be defined instead of having open ended definition.

Compile Dependencies:

<groupId>com.google.code.findbugs</groupId>
<artifactId>jsr305</artifactId>
<version>[1.3.9,)</version>

<groupId>com.google.guava</groupId>
<artifactId>guava</artifactId>
<version>[11.0,)</version>

**Comment by mikesamuel** [comment]
Are there any maven tools for running tests with the latest version and updating version ranges in the POM when they pass?

**Comment by jmanico** [comment]
I don't understand what you're asking for - can you ask again with more
detail?

**Comment by mikesamuel** [comment]
@jmanico The [`versions` plugin](http://www.mojohaus.org/versions-maven-plugin/use-latest-releases-mojo.html) can change dependency versions to point to the latest release version.

That is always going to change each `<version>` tag to a specific version.

I was wondering whether there is an equivalent that just updates the right side of a version range without clobbering the lower bound.

Bonus points if it runs tests to binary search for the greatest version of each dependency for which the tests pass.

**Comment by mikesamuel** [comment]
Closing for lack of response.
