### ISSUE TITLE
Sanitizing Html readers

### ISSUE THREAD

**Issue by mehretaban** [OWASP/java-html-sanitizer#132]
Sanitizer currently supports html string as input which can lead to a significant memory footprint for large html contents also large html contents could have been sent intentionally as a DOS attack for sanitizer. Supporting a Reader (or InputStream) input and buffering the portion of data  could be a useful feature.
Also (large) inner texts of text containers can be passed as separate readers which helps to implement truncation logic without significant effect on heap.

**Comment by davidbarbrowatwork** [comment]
I have a need for this as well, and forked and created a PR for exactly this in the AntiSamy project. Would prefer using this library to AntiSamy. Happy to fork and put up a PR here if that would be welcome.

**Comment by mikesamuel** [comment]
This would only need to affect the HTML lexer, but would be a pretty major change to it.  PRs welcome.
