### ISSUE TITLE
Is it possible to update the CRLF(\r\n) characters with "" character

### ISSUE THREAD

**Issue by vijaysn2702** [OWASP/java-html-sanitizer#136]
Is it possible to update the CRLF(\r\n) characters with "" character, right now HTML Sanitizer allows CRLF characters

Example : 
Input: line \r\n break
HTML Sanitizer output: line \r\n break
Required sanitized output: line   break
Required above output to overcome the CRLF attacks.

Thanks for reporting an issue.

Please report **security vulnerabilities** via
[OWASP's vulnerability rewards program](https://bugcrowd.com/owaspjavasanitizer).

Please report all other feature requests and issues here.

For bugs, please include

  * any input that causes the problem
  * any policy code related to the problem if you can
  * the output you expect

If you're having trouble putting HTML in markdown, try using
an HTML [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/):

```html
HTML goes here
```

**Comment by mikesamuel** [comment]
No.  The sanitizer takes in HTML and produces HTML.  It's not going to take in a C-encoded string that embeds HTML.  That would break existing clients that use it to sanitize HTML that contains code snippets like

```html
You can embed CRLF in a string thus:

<pre>
const string eol("\r\n");
</pre>
```
