### ISSUE TITLE
Incomplete JAR manifest

### ISSUE THREAD

**Issue by veita** [OWASP/java-html-sanitizer#141]
The manifest provided with the JAR is effectively empty. It should at least contain the specification and implementation version to support access through the `java.lang.Package` API.

**Comment by veita** [comment]
The `MANIFEST.MF` of the current `owasp-java-html-sanitizer-20180219.1.jar` has the following content:

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: msamuel
Created-By: Apache Maven 3.5.0
Build-Jdk: 1.8.0_151
```

Consequently, both

```java
  System.out.println(Sanitizers.class.getPackage().getSpecificationVersion());
  System.out.println(Sanitizers.class.getPackage().getImplementationVersion());
```

report `null`.

The implementation version should report `20180219.1` in this case, and the specification version an appropriate version of the specification this library follows.

Ref.:
https://docs.oracle.com/javase/tutorial/deployment/jar/packageman.html

**Comment by mikesamuel** [comment]
The manifest should now include OSGI fields
