### ISSUE TITLE
How to not to sanitize emoji

### ISSUE THREAD

**Issue by sanitizer342343** [OWASP/java-html-sanitizer#143]
I need html sanitizer to sanitize all user inputs expect emoji.
For example,😞 is sanitized to `&#x1f61e;` , is there a way not to do it?

**Comment by codler** [comment]
I wonder also

**Comment by codler** [comment]
@mikesamuel here is my use case https://jsfiddle.net/yjhcq6ts/

**Comment by mikesamuel** [comment]
That seems to do a lot of stuff with React.  I'm not sure how the sanitizer is involved.

```html
<input value=&#x1f61e;>
```

seems to work in the browsers I've tried.

**Comment by vasigorc** [comment]
I have similar issue, this: 
👩🏻

is being converted to:
&#x1f469;&#x1f3fb;

I think this issue echoes with the closed https://github.com/OWASP/java-html-sanitizer/issues/84 The problem for me is that I cannot rely on java-html-sanitizer as a backend tool for _validating_ input. I.e. it seems unpractical to use it for preventing intention of saving malicious (from XSS point of view) strings to the DB.

Correct me if I am wrong.

**Comment by mikesamuel** [comment]
@vasigorc The sanitizer is not meant for validating input.

**Comment by vasigorc** [comment]
@mikesamuel Thank you, could you please suggest a java library for validating input against XSS attacks?

**Comment by mikesamuel** [comment]
I don't know of one.  Filtering HTML is a much harder problem than converting unsafe HTML to safe HTML.  See https://medium.com/@mikesamuel/if-we-knew-what-bad-looked-like-security-wouldnt-be-hard-5cf5b7d54a8
