### ISSUE TITLE
Error sanitizing  with --> in <script> tag

### ISSUE THREAD

**Issue by jvbrandis** [OWASP/java-html-sanitizer#153]
There seems to be a bug in the sanitizer when sanitizing script tags which contains a HTML comment end tag.

We generate a JSON blob which is inserted into a <script> tag of type application/json, and our HTML policy allows script tags of this type, with text content. However, in certain cases, the JSON contains a value string which looks like a HTML comment end, e.g. "cause --> effect".
(see test case scriptTagWithCommentBlockContainingHtmlCommentEnd)

When this happens, the sanitizer completely drops the entire text contents of the script tag.
This happens regardless of whether the text contents are surrounded by a HTML comment block
(see test case scriptTagWithoutCommentBlockContainingHtmlCommentEnd).
There is also no event fired at the HtmlChangeListener when this happens.

Escaping the JSON string by escaping the right angular solves the problem, however this is no longer valid JSON. (see scriptTagWithCommentBlockContainingEscapedHtmlCommentEnd).

The following code snippet highlights the problem:

```java
package test;

import org.junit.Test;
import org.owasp.html.HtmlPolicyBuilder;
import org.owasp.html.PolicyFactory;

import java.io.IOException;
import java.util.HashSet;

import static java.util.Collections.singletonList;
import static org.junit.Assert.assertEquals;

public class OwaspSanitationTest {


  @Test
  public void scriptTagWithCommentBlockContainingHtmlCommentEnd() throws IOException {
    String html = "<script type=\"application/json\">\n" +
            "<!--\n" +
            "{\"field\":\"-->\"}\n" +
            "// -->\n" +
            "</script>";
    assertEquals(html, createHtmlSanitizer().sanitize(html));
  }
  @Test
  public void scriptTagWithCommentBlockContainingEscapedHtmlCommentEnd() throws IOException {
    String html = "<script type=\"application/json\">\n" +
            "<!--\n" +
            "{\"field\":\"--\\>\"}\n" +
            "// -->\n" +
            "</script>";
    assertEquals(html, createHtmlSanitizer().sanitize(html));
  }

  @Test
  public void scriptTagWithoutCommentBlockContainingHtmlCommentEnd() throws IOException {
    String html = "<script type=\"application/json\">\n" +
            "{\"field\":\"-->\"}\n" +
            "</script>";
    assertEquals(html, createHtmlSanitizer().sanitize(html));
  }

  private PolicyFactory createHtmlSanitizer() {
    return new HtmlPolicyBuilder()
            //allow scripts of type application/json
            .allowElements((elementName, attrs) -> {
              int typeIndex = attrs.indexOf("type");
              if (typeIndex < 0 || attrs.size() < typeIndex + 1 || !attrs.get(typeIndex + 1).equalsIgnoreCase("application/json"))
                return null;
              return elementName;
            }, "script")
            //allow contents in this script tag
            .allowTextIn("script")
            //keep type attribute in application/json script tag
            .allowAttributes("type").matching(true, new HashSet<>(singletonList("application/json"))).onElements("script")
            .toFactory();
  }
}

```

**Comment by mikesamuel** [comment]
@jvbrandis 
> Escaping the JSON string by escaping the right angular solves the problem, however this is no longer valid JSON.

You can escape '<' in JSON using `\u003c`.
I would recommend escaping HTML metacharacters so that the JSON is *embeddable* per https://github.com/owasp/json-sanitizer#output

The sanitizer assumes that the fragment is not in a foreign element context.  This doesn't usually matter but if you're using `<script>` elements then it does matter because an attacker who can inject a `<svg>` tag earlier can change the way subsequent `<script>` elements are parsed.
See the difference between

```html
     <script>alert('outside svg: &lt;a&gt;');</script>
<svg><script>alert(' inside svg: &lt;a&gt;');</script></svg>
```

which means that `<script>["<!--"` can cause the HTML parser to possibly ignore a subsequent `</script>` leaving the HTML script element open.

> When this happens, the sanitizer completely drops the entire text contents of the script tag.
> This happens regardless of whether the text contents are surrounded by a HTML comment block
> (see test case scriptTagWithoutCommentBlockContainingHtmlCommentEnd).
> There is also no event fired at the HtmlChangeListener when this happens.

This happens because 

https://github.com/OWASP/java-html-sanitizer/blob/f07e44b034a45d94d6fd010279073c38b6933072/src/main/java/org/owasp/html/HtmlLexer.java#L352-L375

which was removed from later versions of the HTML5 spec because it was overly complicated and there was a better fit for what browsers actually did.

That requirement was enforced on rendering at

https://github.com/OWASP/java-html-sanitizer/blob/f07e44b034a45d94d6fd010279073c38b6933072/src/main/java/org/owasp/html/HtmlStreamRenderer.java#L289-L304

None of that is necessary so I'll put a fix out shortly.

**Comment by jvbrandis** [comment]
Thanks a lot Mike. I was looking at the same spec, so I guessed this was where this was coming from, but great thanks for fixing it, and will look into using the JSON sanitizer also.

**Comment by mikesamuel** [comment]
@jvbrandis 

Unfortunately, I can probably allow

```html
<script type="application/json">{"field":"-->"}</script>
```

but I can't allow

```html
<script type="application/json">{"field":"<!--"}</script>
```

per those restrictions so I don't think any fix is going to get at the heart of your issue which, IIUC, is that arbitrary JSON cannot nest in a `<script>` element.

You can simply replace `s/</\u003c/g` and `s/>/\u003e/g` in your JSON though which does embed nicely.

**Comment by jvbrandis** [comment]
I agree, reading the spec we concluded that a full fix on our part must include escaping.

**Comment by jvbrandis** [comment]
Mike; one question: Should the sanitizer maybe notify the HtmlChangeListener for such a change?
It is neither a tagDiscarded or an tagAttributeDiscarded, but it does discard content, so I would expect it to notify a listener?

**Comment by mikesamuel** [comment]
> Mike; one question: Should the sanitizer maybe notify the HtmlChangeListener for such a change?
It is neither a tagDiscarded or an tagAttributeDiscarded, but it does discard content, so I would expect it to notify a listener?

Good point.  Filed as issue #155.
