### ISSUE TITLE
All-in-one version with shaded guava

### ISSUE THREAD

**Issue by cnsgithub** [OWASP/java-html-sanitizer#157]
Hi,

I'd like to use owasp-java-html-sanitizer in PrimeFaces (a popular JSF component suite). However, because of very restrictive policies regarding the use of third-party policies my PR cannot be merged.

The problem is the dependency to guava, which is a really big one that is also widely used and therefore version conflicts are conceivable.

So I come to the question if it would be possible for you to provide an additional all-in-one version of owasp-java-html-sanitizer having the guava dependency shaded?

Please see https://github.com/primefaces/primefaces/issues/3214 for the reasons why my PR was reverted.

Thanks.

**Comment by JacobPozaic** [comment]
Just for the sake of documenting collisions, OWASP using guava 19.0 makes it incompatible with graphql-java-tools 5.2.4, and graphql-java-servlet 6.2.0.

**Comment by jmanico** [comment]
Duly noted. Thank you for this update.

- Jim

**Comment by tandraschko** [comment]
@mikesamuel 
is there a possibilty to move away from guava?
other owasp libs (like esapi or encoder) doesn't use guava AFAICS

**Comment by fr4x1nu5** [comment]
Used guava imports: https://github.com/OWASP/java-html-sanitizer/search?p=1&q=in%3Afile+%22import+com.google%22&unscoped_q=in%3Afile+%22import+com.google%22

**Comment by commodis** [comment]
Most imports seem to be optional after using Java 8+ and reimplement some functionality

**Comment by stolp** [comment]
After having this open for almost five years now *and* a having pull request #272 open for resolving it, could you please reconsider removing this dependency?

**Comment by seinecle** [comment]
still interested in this issue: Primefaces is using this sanitizer and as a result it gets Guava on board. Any way that Guava can be ditched? Thank you!
