### ISSUE TITLE
Add means to log changes that occur during sanitization

### ISSUE THREAD

**Issue by Thunderforge** [OWASP/java-html-sanitizer#159]
We would like to be able to log the changes that occur during sanitization. For instance, if we begin with 

```html
<foo><b>Text</b></foo>
```

And after sanitization end with 

```html
<b>Text</b>
```

We would like to be able to log that the `<foo>` open and close tags were removed.

I don't know if the best solution would be to either just have a built-in logging, or to provide a hook where arbitrary code can be executed when a tag is removed (perhaps a user might want to throw an error?). But this would be very much appreciated.

**Comment by Thunderforge** [comment]
According to [this mailing list topic](https://groups.google.com/forum/#!topic/owasp-java-html-sanitizer-support/rEajyCZz34o), it should be possible with the help of a [HtmlChangeListener](https://static.javadoc.io/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer/20180219.1/org/owasp/html/HtmlChangeListener.html). It would be helpful to add documentation or an example showing this.

**Comment by mikesamuel** [comment]
Thanks.  Added at https://github.com/OWASP/java-html-sanitizer#telemetry
