### ISSUE TITLE
HTML Sanitizer incorrectly encodes URL in attributes

### ISSUE THREAD

**Issue by rbgarcia** [OWASP/java-html-sanitizer#166]
Hi,

Please consider the following input:
`<a href='https://server/app/page.aspx?GUID=123'/>`

using this policy:
```
new HtmlPolicyBuilder()
    .allowAttributes("href")
    .matching(ONSITE_OR_OFFSITE_URL)
    .onElements("a")
    .allowStandardUrlProtocols()
    .allowElements("a")
    .toFactory();
```

I'm expecting the output to be the same as the input: 
`<a href='https://server/app/page.aspx?GUID=123'/>`

bu what I'm seeing is:
`<a href="https://server/app/page.aspx?GUID&#61;123"></a>`

I'm struggling to understand why is = being encoded when inside an URL because this is currently producing and invalid link.

Also, is there any way to prevent this from happening?
And more importantly, why is this the default behavior?

Thank you.

**Comment by mikesamuel** [comment]
> this is currently producing and invalid link.

On what browser is the link invalid?

When I run the below in my browser console, I get 2 `true`s.

```js
const unencodedUrl = 'https://server/app/page.aspx?GUID=123';
const encodedUrl = unencodedUrl.replace(/=/g, `&#${'='.charCodeAt(0)};`);

for (let url of [ unencodedUrl, encodedUrl ]) {
  const div = document.createElement('div');
  console.group(div.innerHTML = `<a href="${ url }"></a>`);
  const a = div.querySelector('a');
  console.log(a.href === unencodedUrl);
  console.groupEnd();
}
```

**Comment by mikesamuel** [comment]
Closing for lack of response.
