### ISSUE TITLE
Allow all policy

### ISSUE THREAD

**Issue by sergeyk93** [OWASP/java-html-sanitizer#169]
Hi everyone,

First of all thanks for this great library!
I'd like to ask for an enhancement of having an allow all policy. Our business requirements disallow us to sanitize any text and we have to use validation to protect ourselves against XSS.
Judging by the following document:
https://github.com/OWASP/java-html-sanitizer/blob/master/docs/html-validation.md

The right way to validate our input for XSS would be to compare an allow all policy to our customized one and check if they are equal. There's no conventional way of doing that except for defining a policy that allows all the tags and all the attributes in the world.

It would be nice to have either a policy that allows everything by default(including dangerous tags like script) or to have a functionality that does all the encoding and replacements(like changing a single quote to quotes in attribute values or trimming white spaces for attribute values) that will allow to compare the strings after applying our customized policy, in both cases actually the solution proposed in the link can be improved to just comparing the lengths of the strings.

Any thoughts? Maybe I'm missing something and a functionality like this does exist?

**Comment by mikesamuel** [comment]
My thoughts on validation are at https://github.com/OWASP/java-html-sanitizer/blob/master/docs/html-validation.md

In short, restricting yourself to validation ties implementors hands and validators have little room to maneuver if a security researcher finds a novel way to confuse HTML parsers.

**Comment by mikesamuel** [comment]
If you want the string that would result from a policy that allows everything, you can just define your own policy.

```java
StringBuilder htmlOutput = new StringBuilder();
HtmlStreamRenderer renderer = HtmlStreamRenderer.create(htmlOutput, () -> {});
TagBalancingHtmlStreamEventReceiver balancer = new TagBalancingHtmlStreamEventReceiver(renderer);
HtmlSanitizer.sanitize(htmlInput, new HtmlSanitizer.Policy() {
  public void openDocument() {
    balancer.openDocument();
  }
  public void openTag(String tagName, List<String> attrs) {
    balancer.openTag(tagName, attrs);
  }
  public void text(String text) {
    balancer.text(text);
  }
  public void closeTag(String tagName) {
    balancer.closeTag(tagName);
  }
  public void closeDocument() {
    balancer.closeDocument();
  }
});
```

Just be aware, there's no reason to believe that just because htmlOutput is the same regardless of policy, does not mean the browser will interpret htmlInput the same way.

For example `<noframes><script>alert(1)</script></noframes>` arguably has no script element, but if parsed as the content of a sandboxed iframe that disallows frames but allows scripts, it may be interpreted as containing a script element.

**Comment by sergeyk93** [comment]
Thanks mike! We're very strict with the tags and attributes we allow in general(let alone XSS prone tags/attributes), so our approach is to address XSS as a private case for our HTML user input validation in general.
