### ISSUE TITLE
Sanitizer stripping the 'id' attribute

### ISSUE THREAD

**Issue by ManoharMS** [OWASP/java-html-sanitizer#188]
When we are trying to sanitize the below html string, the sanitizer is stripping the 'id' attribute and adding it to the discardedAttributesMap and isValidHtmlString returns false.

htmlString: ```<p id="scot1">test<br></p>```

```
private static final PolicyFactory policy = Sanitizers.FORMATTING.and(Sanitizers.LINKS).and(Sanitizers.BLOCKS).and(Sanitizers.STYLES);

private boolean isValidHtmlString(String htmlString) {
        CVHtmlChangeListener cvHtmlChangeListener = new CVHtmlChangeListener();
        String safeHtmlValue = policy.sanitize(htmlString, cvHtmlChangeListener, cvHtmlChangeListener);
        if(!cvHtmlChangeListener.getDiscardedTagsList().isEmpty() || !cvHtmlChangeListener.getDiscardedAttributesMap().isEmpty() || safeHtmlValue.isEmpty()) {
            return false;
        }
        return true;
    }

public class CVHtmlChangeListener implements HtmlChangeListener {
    private List<String> discardedTagsList;
    private Map<String, List<String>> discardedAttributesMap;

    CVHtmlChangeListener(){
        discardedTagsList = new ArrayList<>();
        discardedAttributesMap = new HashMap<>();
    }

    public List<String> getDiscardedTagsList() {
        return discardedTagsList;
    }

    public Map<String, List<String>> getDiscardedAttributesMap() {
        return discardedAttributesMap;
    }

    @Override
    public void discardedTag(@Nullable Object context, String elementName) {
        if(context != null){
            discardedTagsList.add(elementName);
        }
    }

    @Override
    public void discardedAttributes(@Nullable Object context, String tagName, String... attributeNames) {
        if(context != null){
            List<String> attributesList = new ArrayList<>(attributeNames.length);
            for (String attribute:attributeNames) {
                attributesList.add(attribute);
            }
            discardedAttributesMap.put(tagName, attributesList);
        }
    }
```
Question 1: We would like to understand/know why 'id' tag is stripped from the above html string? 
Question 2: For now as a workaround we have updated our policy as below:
```
private static final PolicyFactory policyForAttributes = new HtmlPolicyBuilder().allowCommonBlockElements().allowCommonInlineFormattingElements().allowAttributes("id").globally().toFactory();
    private static final PolicyFactory policy = Sanitizers.FORMATTING.and(Sanitizers.LINKS).and(Sanitizers.BLOCKS).and(Sanitizers.STYLES).and(policyForAttributes);
```
But this solves for only 1 attribute. Is there a list of allowed attributes? so that we create a whitelist of allowed attributes to build our own policy?

**Comment by mikesamuel** [comment]
> ```java
> private static final PolicyFactory policy = Sanitizers.FORMATTING.and(Sanitizers.LINKS).and(Sanitizers.BLOCKS).and(Sanitizers.STYLES);
> ```

> Question 1: We would like to understand/know why 'id' tag is stripped from the above html string?

The sanitizer API requires you to explicitly allow something.  Nothing in the above allows the `id` attribute.
The [javadoc for *HtmlPolicyBuilder*](https://javadoc.io/doc/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer/20160924.1/org/owasp/html/HtmlPolicyBuilder.html) notes:

> ### Rules of thumb
>
> * Everything is denied by default. There are `disallow`… methods, but those reverse allows instead of rolling back overly permissive defaults.
> * ...

----

> But this solves for only 1 attribute. Is there a list of allowed attributes? so that we create a whitelist of allowed attributes to build our own policy?

Yes.  You can allow multiple attributes as in

```java
private static final PolicyFactory policyForAttributes = new HtmlPolicyBuilder()
    .allowCommonBlockElements()
    .allowCommonInlineFormattingElements()
    .allowAttributes("id").globally()
    .allowAttributes("class").globally()
    .toFactory();
```

or you can pass multiple attribute names to a single `.allowAttributes(...)` call as in

```java
private static final PolicyFactory policyForAttributes = new HtmlPolicyBuilder()
    .allowCommonBlockElements()
    .allowCommonInlineFormattingElements()
    .allowAttributes("id", "class").globally()
    .toFactory();
```

The [javadoc](https://javadoc.io/doc/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer/20160924.1/org/owasp/html/HtmlPolicyBuilder.html#allowAttributes-java.lang.String...-) for `allowAttribute` explains how it works in more detail.
