### ISSUE TITLE
hsl() is not a predefined default CSS function

### ISSUE THREAD

**Issue by KirillMakrutin** [OWASP/java-html-sanitizer#212]
By default, **rgb** and **rgba** functions are allowed, but not **hsl**:
input:

```html
<div style="color: rgb(255, 0, 0)">rgb</div>
<div style="color: rgba(255, 0, 0, 1)">rgba</div>
<div style="color: hsl(0, 100%, 50%)">hsl</div>
```

output (using default CSS schema):

```html
<div style="color:rgb( 255 , 0 , 0 )">rgb</div>
<div style="color:rgba( 255 , 0 , 0 , 1 )">rgba</div>
<div>hsl</div>
```

Can it be expected that hsl function will be preserved?

**Comment by mikesamuel** [comment]
Yes.  We can support hsl.

hsla while we're at it:

https://www.w3.org/TR/css-color-3/#hsla-color
