### ISSUE TITLE
How to give input to jar file and get the processed output?

### ISSUE THREAD

**Issue by pr0t0nus3rxyz** [OWASP/java-html-sanitizer#233]
I am not able to run the jar file directly even with java -cp owasp-java-html-sanitizer-20160924.1.jar org.owasp.html.HtmlSanitize.
It says main method not found. Can anyone please share how can i run the jar file and give input with sanitized output.

Thanks in advance

**Comment by jmanico** [comment]
This will help!

https://github.com/OWASP/java-html-sanitizer/blob/master/docs/getting_started.md

--
Jim Manico
@Manicode

**Comment by mikesamuel** [comment]
This isn't really a command line tool since there's no way to specify a policy from the command line.  You should be able to create a main class that uses a policy of your choosing easily enough though.
