### ISSUE TITLE
Html sanitizer repeatedly adds rel="noopener noreferrer" even if it's pre-exist

### ISSUE THREAD

**Issue by anudhuri23** [OWASP/java-html-sanitizer#306]
Thanks for reporting an issue.

Please report **security vulnerabilities** via
[OWASP's vulnerability rewards program](https://bugcrowd.com/owaspjavasanitizer).

Please report all other feature requests and issues here.

_**### So we are using OWASP/java-html-sanitizer to sanitize the html. It adds noopener noreferrer everytime we sanitize it. It should not add noopener noreferrer if it's already exists in the HTML.**_

**Also note that we have already upgraded the jar to latest one i.e owasp-java-html-sanitizer-20220608.1.jar**

For bugs, please include
**Input**
````
```
<p dir="ltr"><a href="http://bbbbb" rel="noopener noreferrer" target="_blank">www.bbbbbbb.com</a></p>
```
````
**Output I am getting right now**
````
```
<p dir="ltr"><a href="http://bbbbb" rel="noopener noreferrer noopener noreferrer" target="_blank">www.bbbbbbb.com</a></p>
```
````

**Expected output**
````
```
<p dir="ltr"><a href="http://bbbbb" rel="noopener noreferrer" target="_blank">www.bbbbbbb.com</a></p>
```
````

**### Note**
I found similar issue https://github.com/OWASP/java-html-sanitizer/issues/145 here which is very old issue but it's not resolved yet. Hence creating new one. Please help me on resolving it. It's urgent

If you're having trouble putting HTML in markdown, try using
an HTML [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/):

**Comment by mikesamuel** [comment]
Fixed in e8aa0f1b75ab81eea97ef173fefc023a3e16963d
