### ISSUE TITLE
CENTER in H1 terminates header

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OWASP/java-html-sanitizer#33]
a.chichikov@semrush.com says

We have a similar behavior in this case:

```Java
assertEquals("<h1>TEXT</h1>", 
Sanitizers.BLOCKS.sanitize("<H1><center>TEXT</H1>"));
```

For this one the result is:

```html
<h1></h1>TEXT
```

instead of:

```html
<h1>TEXT</h1>
```

But test case:

```Java
assertEquals("<h1>TEXT</h1>", 
Sanitizers.BLOCKS.sanitize("<H1></center>TEXT</H1>"));
```

works as expected:

```html
<h1>TEXT</h1>
```

What's wrong with the first one?

Original issue reported on code.google.com by `mikesamuel@gmail.com` on 1 Oct 2014 at 12:46

**Comment by jmanico** [comment]
Bump to take a look at this.

**Comment by mikesamuel** [comment]
AFAICT, this is behaving correctly.

Given `<!doctype html><html><head><title>.</title><body><H1><center>TEXT</H1>`, https://validator.w3.org/nu/#textarea says

> Element center not allowed as child of element h1 in this context. (Suppressing further errors from this subtree.)
