### ISSUE TITLE
font-family not well-formed after sanitizing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OWASP/java-html-sanitizer#34]
What steps will reproduce the problem?

HTML before sanitizing

```html
<span style="font-size:9.0pt;font-family:"Trebuchet MS","sans-serif";color:#505050">
```

HTML after sanitizing

```html
<span style="font-size:9pt;font-family:'trebuchet ms' ,;color:#505050">
```

I already read in other issues, why the sans-serif font will be dropped. This 
would be fine, but there is a "," left after removing the font.
Firefox struggles with this "," and will not use any of the provided Fonts.

So the expected Output is:

```html
<span style="font-size:9pt;font-family:'trebuchet ms' ;color:#505050">
```

When removing the "," Firefox renders the page as expected.

What version of the product are you using? On what operating system?

r239, Windows 8.1, Firefox 32.0.3
No Issue in Internet Explorer and Chrome.

Original issue reported on code.google.com by `dominik....@verdestron.de` on 26 Oct 2014 at 12:21

**Comment by jmanico** [comment]
Bump to take a look at this.

**Comment by mikesamuel** [comment]
```html
<span style="font-size:9.0pt;font-family:"Trebuchet MS","sans-serif";color:#505050">
```

has double quotes around Trebuchet MS which close the attribute, so this is equivalent to

```html
<span style="font-size:9.0pt;font-family:" trebuchet="" ms","sans-serif";color:#505050"="">
```

so the reason that those font-names are dropped is because they're never in the `style` attribute's value to begin with.
