### ISSUE TITLE
documentation: maven.md has old version number

### ISSUE THREAD

**Issue by tibistibi** [OWASP/java-html-sanitizer#41]
i tried installing the java-html-sanitizer with the example from the maven.md file.
maven gave download problems for some old versions. 
changing the version to 
			&lt;version>[r239,)&lt;/version>
solved the problem

only minor issue but should help out outers.

**Comment by mikesamuel** [comment]
Thanks.   https://github.com/OWASP/java-html-sanitizer/commit/7122b56885d6224dbf3c761390b504b1efd114ca

**Comment by tibistibi** [comment]
its a small step towards perfection.
