### ISSUE TITLE
Latest Maven Version?

### ISSUE THREAD

**Issue by markrichardsft** [OWASP/java-html-sanitizer#42]
Hi, great work but I've noticed something strange in mvn repostiory and hope you can help and possibly update your release version numbers.

If you look in mvn repository you can see a release this year: 
http://mvnrepository.com/artifact/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer/20150501.1

But the page is recommending that a newer release is available from last year !?
http://mvnrepository.com/artifact/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer/r239

And the OWASP page for the project suggests last year's version is the latest:
https://www.owasp.org/index.php/OWASP_Java_HTML_Sanitizer_Project

Please advise whether the 2015 one is a release (or just a beta/alpha unstable thing).

If it is a release, then please change your versioning of the pom to ensure that the latest version is recognised as the latest version by maven tooling. This might be due to ascii string comparison of the version number: ie 
'r' > '2'
"r239" > "20150501.1"

I'm not sure what impact this would have for example if auto versioning picks latest or maven enforcer warns about latest: because it seems like latest they might suggest the 2014 one and not the 2015 one by maven version conventions: (this might need testing). Therefore users attempting to use latest may get trapped on an old version.

**Comment by jmanico** [comment]
I forgot to update the wiki during the last update. I'm review all this later today, my apologies!

--
Jim Manico
@Manicode
(808) 652-3805

**Comment by mikesamuel** [comment]
I'm working on getting a new version out and will use a more sensible numbering scheme.

**Comment by jmanico** [comment]
I think this was fixed a long while ago. Is it ok to close this issue?
