### ISSUE TITLE
Can't seem to whitelist <span> without attributes

### ISSUE THREAD

**Issue by jpetren** [OWASP/java-html-sanitizer#46]
The following code:

```java
StringBuilder retVal = new StringBuilder();

PolicyFactory policyFactory = new HtmlPolicyBuilder().allowElements("b", "i", "br", "p").allowWithoutAttributes("span").toFactory();
    	
HtmlStreamRenderer renderer = HtmlStreamRenderer.create(retVal, 
                                                        new Handler<String>() {
                                                        	public void handle(String x) {
                                                        		throw new AssertionError(x);
                                                        	}
                                                        });
    	
HtmlSanitizer.sanitize("<span>foo</span>", policyFactory.apply(renderer));
```

Returns `"foo"`, not `"<span>foo</span>"`

**Comment by mikesamuel** [comment]
You've never allowed the "span" element.

**Comment by jpetren** [comment]
did you scroll right?  i did an allowWithoutAttributes.  I initially put it in allowElements but it didn't work; then i found these bugs and thought allowWithoutAttributes would solve my problem.

**Comment by mikesamuel** [comment]
Sorry.  The docs could be clearer on that.  I'll reopen this as a doc bug.

**Comment by jmanico** [comment]
Mike or jpetren, can you send me the final policy that illustrates this issue (done right) and I'll handle the doc fix in various locations? Thank you!

**Comment by jpetren** [comment]
policyFactory = new HtmlPolicyBuilder()                                  .allowWithoutAttributes("span").allowElements("span").toFactory();

**Comment by mikesamuel** [comment]
The following runs green:

```java
  @Test public static final void testIssue46() {
    PolicyFactory s = new HtmlPolicyBuilder()
        .allowWithoutAttributes("span")
        .allowElements("span")
        .toFactory();

    String unsafe = "<span onclick=alert(1337)>Foo</span>";

    String safe = "<span>Foo</span>";

    String sanitized = s.sanitize(unsafe);

    assertEquals(safe, sanitized);
  }
```

**Comment by nfalco79** [comment]
Hi @mikesamuel , in this example where I use default sanitiers the span element does not work, it is cutted

```    @Test
public void testIssue46() {
    PolicyFactory s = Sanitizers.FORMATTING;
    String toTest = "<span>Foo</span>";
    String safe = "<span>Foo</span>";
    String sanitized = s.sanitize(toTest);
    assertEquals(safe, sanitized);
}
```

I got `org.junit.ComparisonFailure: expected:<[<span>Foo</span>]> but was:<[Foo]>`

the Sanitizers.FORMATTING is `new HtmlPolicyBuilder().allowCommonInlineFormattingElements().toFactory()` where allowCommonInlineFormattingElements is `allowElements(
        "b", "i", "font", "s", "u", "o", "sup", "sub", "ins", "del", "strong",
        "strike", "tt", "code", "big", "small", "br", "span", "em")`
