### ISSUE TITLE
Project Version in POM Seems to Be Incorrect

### ISSUE THREAD

**Issue by EarthCitizen** [OWASP/java-html-sanitizer#47]
The project version in the pom is 1.1-SNAPSHOT, but a release of 1.1 exists on Maven Central. If the release of 1.1 is valid on Maven Central, then the version in the pom should be 1.2-SNAPSHOT.

**Comment by mikesamuel** [comment]
Thanks.  Fixed at https://github.com/OWASP/java-html-sanitizer/commit/94d7533ef8a9f46034b7a3c2d4c299c3c9cf1054
