### ISSUE TITLE
Text alternative in video-element

### ISSUE THREAD

**Issue by mikesamuel** [OWASP/java-html-sanitizer#53]
Johannes Lichtenberger writes

I have the following policy: 

``` java
    /**
     * Allow media elements/attributes.
     */
    public static final PolicyFactory MEDIA = new HtmlPolicyBuilder().allowElements("video", "audio", "source")
            .allowAttributes("controls", "width", "height").onElements("video").allowAttributes("controls")
            .onElements("audio").allowAttributes("src", "type").onElements("source").allowTextIn("video", "audio")
            .toFactory();
```

and the HTML content I want to sanitize (all whitelisted content) is:

``` html
<p><video controls="controls" width="300" height="150">
<source src="media/video/small.webm" type="video/webm" />
<source src="media/video/small.mp4" type="video/mp4" />
<source src="media/video/small.ogv" type="video/ogg" />
<source src="media/video/small.3gp" type="video/3gp" />
Your browser does not support the video tag.</video></p>
```

But it seems character content within the video-element is never permitted (contents-member field is 0, probably it should be != 0?). Should be valid to have an alternative text I guess.

**Comment by jmanico** [comment]
Bump asking Mike to take a peek at this. We also love patches so please consider submitting a patch for consideration!
Aloha,
Jim

**Comment by mikesamuel** [comment]
This affects `<video>` and other new tags as well.

The problem is that the table [`ElementContainmentRelationships`](https://github.com/OWASP/java-html-sanitizer/blob/master/src/main/java/org/owasp/html/TagBalancingHtmlStreamEventReceiver.java#L349) is long due for an overhaul to take into account the many changes in the HTML5 spec.
Even if text is added to the allowed content for `<audio>` and `<video>`, `<track>` and `<source>` elements would still be missing.

I asked http://stackoverflow.com/questions/41110211 to see if I can find a source of data to do that.

**Comment by mikesamuel** [comment]
I implemented a scheme that I think addresses this.  Will post to the public list since it is not a minor update.

**Comment by pickle-weasle** [comment]
Pretty sure this is working now. We were seeing text within audio/video tags getting moved to outside the tags, but this has been resolved in the newest release
