### ISSUE TITLE
PolicyFactory Sanitize method weird output

### ISSUE THREAD

**Issue by xeno6696** [OWASP/java-html-sanitizer#54]
Somehow this issue got listed against ESAPI.  Don't know if there's history for that, but it doesn't seem to belong with the ESAPI project.  

From Toombs....@gmail.com on February 07, 2014 14:39:06

What steps will reproduce the problem?

1. Create PolicyFactory with all added sanitizers (Formatting/Images/Links/Styles/Blocks)
2. Pass `"<b><h1>text</h1></b>"` to the `PolicyFactory.sanitize(String html)`
3. Result returned is `"<b></b><b><h1>text</h1></b>"`

Expected `"<b><h1>text</h1></b>"` 

Received `"<b></b><b><h1>text</h1></b>"`

What version of the product are you using? On what operating system? -Windows 7 64-bit
-Maven dependency:

com.googlecode.owasp-java-html-sanitizer
owasp-java-html-sanitizer
r209

Does this issue affect only a specified browser or set of browsers? -This is browser unrelated, testing simply through JUnit tests Please provide any additional information below. I am currently using this method in a loop and exiting the loop when the string has been fully sanitized based on the idea that it will be sanitized when the previous sanitization result will equal the current sanitization result. Unfortunately, with this issue, on some inputs the sanitize method does not stop adding tags resulting in an infinite loop because the previous sanitization of the string will never equal the current sanitization of the string.

Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=318

**Comment by mikesamuel** [comment]
Yeah.  Inline elements can't contain block elements which is why this is weird.  

> I am currently using this method in a loop and exiting the loop when the string has been fully sanitized based on the idea that it will be sanitized when the previous sanitization result will equal the current sanitization result.

Whatever result comes out of the sanitizer is sanitized.  You don't need to run the method multiple times.

**Comment by jmanico** [comment]
Can you please try this against the latest release v239? https://search.maven.org/remotecontent?filepath=com/googlecode/owasp-java-html-sanitizer/owasp-java-html-sanitizer/r239/owasp-java-html-sanitizer-r239.jar

**Comment by xeno6696** [comment]
I created the following Unit Test that reproduces the problem:

```
  @Test
  public static final void testIssue54() {
    PolicyFactory sanitizer = Sanitizers.FORMATTING
      .and(Sanitizers.BLOCKS).and(Sanitizers.STYLES).and(Sanitizers.LINKS).and(Sanitizers.IMAGES);
    String input = "<b><h1>text</h1></b>";
    String got = sanitizer.sanitize(input);
    String want = "<b><h1>text</h1></b>";
    assertEquals(want, got);
  }

```

I ran the test against a fresh clone, in the SanitizersTest.java file.

**Comment by mikesamuel** [comment]
`<b><h1>text</h1></b>` is misnested HTML so is probably not what we want to output

**Comment by xeno6696** [comment]
Works for me, close it.
