### ISSUE TITLE
Special treatment of '{' character, which adds a comment at the end

### ISSUE THREAD

**Issue by spinscale** [OWASP/java-html-sanitizer#55]
Sorry, if I should have used the mailing list for this kind of questions, if so, please just close this bug and I will go ahead there, but it feels to me like an issue. When the `{` character is being sanitized, a comment is appended to it all the time. This breaks in `20151202.2`, but used to work in `r239` (havent tested any versions in between, just wanted to upgrade that dependency in my code).

Consider this unit test:

```java
    public void testThatPlaceHoldersAreNotReplaced() {
        PolicyFactory policyFactory = new HtmlPolicyBuilder().toFactory();
        assertThat(policyFactory.sanitize("<b>bold</b>"), is("bold"));
        assertThat(policyFactory.sanitize("test"), is("test"));
        assertThat(policyFactory.sanitize("%"), is("%"));
        assertThat(policyFactory.sanitize("~"), is("~"));
        assertThat(policyFactory.sanitize("{"), is("{"));
    }
```

breaks with

```
java.lang.AssertionError: 
Expected: is "{"
     but: was "{<!-- -->"
Expected :{
Actual   :{<!-- -->
```

I see that `HtmlStreamRenderer.writeText` appends the comment and that logic is different in `r239`.

Pointers appreciated and thanks for the hard work!

**Comment by mikesamuel** [comment]
This change was effected in https://github.com/OWASP/java-html-sanitizer/commit/4f9a7af04a906d03ce75561f513cf7b151025193#diff-4685b71e19e2f1de0ad0098cc62d6dbb .  See https://github.com/OWASP/java-html-sanitizer/blob/master/docs/client-side-templates.md for an explanation.
