### ISSUE TITLE
Mustache templating variables are tweaked during sanitizing

### ISSUE THREAD

**Issue by arjunvj** [OWASP/java-html-sanitizer#56]
Here is a very simple usecase to demonstrate the issue.

```java
PolicyFactory policy =
        Sanitizers.BLOCKS
            .and(Sanitizers.FORMATTING)
            .and(Sanitizers.IMAGES)
            .and(Sanitizers.LINKS)
            .and(Sanitizers.TABLES)
            .and(Sanitizers.STYLES);
String toSanitize = "{{test}}";
System.out.println(policy.sanitize(toSanitize));
```

> **Output:** ```{<!-- -->{test}}```

Another example.
> **Input**: ```<span style="font-size: medium;">{{fName}} {{lName}}</span>```
> **Ouput**: ```<span style="font-size:medium">{<!-- -->{fName}} {<!-- -->{lName}}</span>```

This seems to be happening since v1.1 release. I assume this isn't a intentional behavior.

**Comment by arjunvj** [comment]
Just noticed that the issue prior to this is also reporting the same. Closing this.

Comments in the issue #55 
>> This change was effected in 4f9a7af#diff-4685b71e19e2f1de0ad0098cc62d6dbb . See https://github.com/OWASP/java-html-sanitizer/blob/master/docs/client-side-templates.md for an explanation.

**Comment by mikesamuel** [comment]
Do you have a use-case for preserving mustache variable references in the sanitized output?

**Comment by arjunvj** [comment]
Yes! Thanks for your interest on this.

We build custom HTML widgets.
We have this scenario where the data comes from a REST service and the initial rendering of the HTML widgets happen on the server. As part of end user interactions with the HTML widget, further rendering can happen on client.

While these HTML widgets do most of the presentation work and data handling, we do give the widget users some hooks to present the data in certain 'customizable' sections. The widget users do this by providing **HTML with embedded Mustache template variables**.

While rendering the widget on client, these Mustache variables help the widget user to present the data in the 'customizable' sections.

The widget user embedded HTML is what is sanitized using this project (All the security aspects are ensured by our widget/framework, and is not left as a responsibility of widget user). With the sanitizer not allowing the client template variables, we're restricted from upgrading to the latest release.

(Widget user - Not end user, a application developer building webapps using our widgets)

**Comment by mikesamuel** [comment]
Is it the case that all the allowed mustache expressions are all simple variable substitutions and that the names that can be dereferenced are white-listed?

Why sanitize the widget user's mustache template instead of sanitizing the HTML output from mustache?

**Comment by arjunvj** [comment]
* All mustache expressions are allowed except the HTML-unescaped ones - `{{{...}}}` and `{{ & ...}}`.

* It isn't easy to come up with a white-list of dereferenced variable names. Instead would it be better to pass in a list of allowed expressions (or a pattern of allowed expressions, e.g. `allow("{{.*}}")`?

* Sanitizing on the client after mustache template evaluation was considered. There are two reasons we're not doing this way
  * Sanitizing the template on server and disallowing HTML unescaped expressions would be safe.
  * Sanitizing on the client is a performance bottleneck is certain cases. One major usecase is in a widget that works similar to https://twitter.github.io/typeahead.js/ . Using the Mustache templates, the widget user can customize the appearance of suggestions in the dropdown popup. When the suggestions to be displayed are huge, beyond a point, sanitizing per row/suggestion would affect performance even in the fastest of the browsers.
