### ISSUE TITLE
Prepackaged Policy: Event sanitizer, safe output for attributes

### ISSUE THREAD

**Issue by aabashkin** [OWASP/java-html-sanitizer#57]
The suggestion is to create a prepackaged policy that will filter out JavaScript events such as onmouseover, onfocus, etc.

Use case: Assume you would like to safely output some data in an attribute. Currently, the protection here would come from the fact that double quotes are encoded, thus preventing a context breakout. However, let's assume we are applying the HTML sanitizer at input, and [per best practice](http://lukeplant.me.uk/blog/posts/why-escape-on-input-is-a-bad-idea/), don't want to encode data before storing it. Also assume that output encoding is applied manually (i.e. inconsistently) and we can't rely on it. In this case, stripping the events helps prevent XSS.

owasp_sanitizer?input=test" onmouseover=alert(1)

**Comment by jmanico** [comment]
I politely do not think this is a valid bug report. This tool specifically let you pick which tags are acceptable and ALL OTHER markup is removed. All policies will remove JavaScript events unless you explicitly allow them. I am closing this report. If you have any more questions, email the project leads or re-open this issue. Cool?

Aloha,
Jim
