### ISSUE TITLE
Allow "and"ing of policies after initial policy creation

### ISSUE THREAD

**Issue by robertlagrant** [OWASP/java-html-sanitizer#61]
I'd like to expose sanitizing as a web service; is it possible to break out composition of sanitizers so it can be done sequentially? Sample usage:

```
if(blocksPolicy) policy.and(Sanitizers.BLOCKS);
if(stylesPolicy) policy.and(Sanitizers.STYLES);
```

**Comment by mikesamuel** [comment]
You want

    policy = policy.and(...);

per
http://www.javadoc.io/doc/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer/20160203.1

**Comment by robertlagrant** [comment]
Sorry - I missed a key method that lets me do that (I think it's `build()`). My fault!
