### ISSUE TITLE
Using Prepackaged policies with a custom renderer

### ISSUE THREAD

**Issue by boldwade** [OWASP/java-html-sanitizer#66]
Hi, this isn't an issue, but a question. How would one use prepackaged polices in conjuction with a custom renderer? I would like to not have to define all the policies, just use the prepackaged ones but I want to handle render errors so that I can log them on our server. How would this be possible?

Is this possible?

**Comment by mikesamuel** [comment]
Please ask on the mailing list which can be found on the project home page.
