### ISSUE TITLE
open-ended guava dependency has unexpected consequence

### ISSUE THREAD

**Issue by jpetren** [OWASP/java-html-sanitizer#67]
I've been using your sanitizer for a while now but all of a sudden today, I hit an issue while building b/c it pulled down guava 20 which is incompatible with other parts of my project.  

This dependency you have in your pom.xml:

    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>

is wide open and it gets turned into a gradle dependency of of guava [11.0,) (meaning, anything 11.0 or up, as it becomes available). 

Can you lock this dependency down to 11.0 exactly or even 18.0?  Other people I work with have had other issues with guava 20 and I don't think it's trustworthy.  In the meantime, I've had to change my build.gradle to exclude guava from my dependency on your sanitizer:

   compile (group: 'com.googlecode.owasp-java-html-sanitizer', name: 'owasp-java-html-sanitizer', version: '1.+') {
    exclude group: 'com.google.guava'
   }

**Comment by mikesamuel** [comment]
I suppose I could tighten it to [11, 20.0).

I'm unclear what effect specifying

```xml
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>18.0</version>
      <scope>provided</scope>
    </dependency>
```

would have on clients.  IIUC, *provided* dependencies are not enumerated during a transitive dependency download.

**Comment by jpetren** [comment]
if you can determine the earliest version of guava you need, can't you specify that?  if a client needs a later version of guava for something else, it's on them to pull that down, no?

**Comment by mikesamuel** [comment]
I'm not sure I understand.  What do you mean by "pull that down?"

**Comment by jpetren** [comment]
if a client has other dependencies, it's on them to specify (by version number) which ones they need.  including later versions of guava.

**Comment by jmanico** [comment]
So will changing the dependency to the following fix the problem so we can close this out? cc @mikesamuel 
 
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>18.0</version>
      <scope>provided</scope>
    </dependency>

**Comment by mikesamuel** [comment]
Fixed in snapshot : https://github.com/OWASP/java-html-sanitizer/blob/56b9eb6db2c8bb9df01425794eb56d760d61b248/parent/pom.xml#L203
