### ISSUE TITLE
CssSchema allows image() but not url()

### ISSUE THREAD

**Issue by lquinn** [OWASP/java-html-sanitizer#72]
The CssSchema class allows the newfangled "image()" notation in places where I think it intends to allow "url()" as well (or instead). For example:

```java
    ImmutableMap<String, String> backgroundImageFunctions =
      ImmutableMap.<String, String>of(
          "image(", "image()",
          "linear-gradient(", "linear-gradient()",
          "radial-gradient(", "radial-gradient()",
          "repeating-linear-gradient(", "repeating-linear-gradient()",
          "repeating-radial-gradient(", "repeating-radial-gradient()");
```

The image() notation can reference a URL just as the url() notation, but url() is much more commonly used in practice with properties like background-image. Current browsers support only url(), not image().

I think that CssSchema should use url() instead of image().

https://drafts.csswg.org/css-values-3/#url-value
https://drafts.csswg.org/css-images-3/#funcdef-image

**Comment by mikesamuel** [comment]
`url(...)` is not a function, but a [token level structure](https://www.w3.org/TR/CSS2/syndata.html#uri).  It should be recognized by the lexer and allowed where URLs are allowed and rewritten according to the URL policy.

Do you have an example where this is not happening?

**Comment by lquinn** [comment]
When I use `allowStyling()`, the background-image property gets stripped out in the following simple test.

```java
import org.owasp.html.*;

public class sanitizer {
    public static void main(String[] args) {
        PolicyFactory policy = new HtmlPolicyBuilder()
            .allowStandardUrlProtocols()
            .allowStyling()
            .allowElements("div")
            .toFactory();
        String safeHtml = policy.sanitize(
            "<html><head><title>test</title></head><body>" +
            "<div style='color: red; background-image: url(http://example.com/foo.png)'>" +
            "div content" +
            "</div></body></html>");
        System.out.println(safeHtml);
    }
}
```

The output is

```html
<div style="color:red">div content</div>
```

I don't see a way to enable the background-image to get through.

**Comment by mikesamuel** [comment]
The problem is [here](https://github.com/OWASP/java-html-sanitizer/blob/master/src/main/java/org/owasp/html/StylingPolicy.java#L90-92) so it's my fault entirely.  I am amazed that no-one has needed this until now.  Will fix, though with an opt-in so I don't substantially change the behavior of existing policies.

**Comment by mikesamuel** [comment]
https://github.com/OWASP/java-html-sanitizer/commit/f76a8a710277309158afea486077d357e316170f addresses this issue.  I will push a release to central with this fix.

**Comment by mikesamuel** [comment]
Fixed at [20160614.1](http://search.maven.org/#artifactdetails%7Ccom.googlecode.owasp-java-html-sanitizer%7Cowasp-java-html-sanitizer%7C20160614.1%7Cjar)

**Comment by alokob** [comment]
I have found that if latest version of html-sanitizer (20200713.1) is used then this issue exists , found it to be fixed only in version 20160614.1. Is it the case that over the period this particular fix is removed intentionally? Please let me know.

**Comment by mikesamuel** [comment]
@alokob It is not intentional.

The test below still passes for me:

https://github.com/OWASP/java-html-sanitizer/blob/ca406970b74abd03ec045713b3c9f53963b716ff/src/test/java/org/owasp/html/HtmlPolicyBuilderTest.java#L623-L645

How might I go about reproducing the problem you're seeing?

**Comment by alokob** [comment]
@mikesamuel  Thanks for responding.  If url is pointing to base64 encoded image which is embedded in html itself then this issue is observed. Please check below sample code. replace "ivv" in below code with any base64 encoded image , because of limitation on length of chars in comment I cant put my sample image here.  

Please let me know your thoughts.

`public static final void testBackgroundImageWithUrl() {
    PolicyFactory policy = new HtmlPolicyBuilder().allowStandardUrlProtocols().allowStyling()
        .allowUrlsInStyles(AttributePolicy.IDENTITY_ATTRIBUTE_POLICY).allowElements("div")
        .toFactory();
    String unsafeHtml = "<html><head><title>test</title></head><body>" + "<div style='"
        + "color: red; background-image: "
        + "url(data:image/png;base64,ivv);>div content" + "</div></body></html>";
    String safeHtml = policy.sanitize(unsafeHtml);
    System.out.println(safeHtml);

  }`

Stay Safe.

**Comment by alokob** [comment]
@mikesamuel  Please can you share your inputs on why the inline base64 encoded images are not working ? I have even tried adding .allowUrlProtocols("data") to the policy , but no success. Same code works fine with version "20160614.1".
