### ISSUE TITLE
Html getting mangled when removing <style> tag

### ISSUE THREAD

**Issue by edbaker83** [OWASP/java-html-sanitizer#76]
Removing the style tag seems to be mangling the html in the process.
The html
`<table><tr><td>a</td></tr><style></style><tr><td>b</td></tr></table>`

Is sanitized to this
`<table><tr><td>a</td></tr></table><tr><td>b</td></tr>`

**Comment by edbaker83** [comment]
Not sure if this is the ideal approach but it does address the issue raised by giving the style tag the same properties as the script tag

[style_fix.patch.txt](https://github.com/OWASP/java-html-sanitizer/files/341722/style_fix.patch.txt)

**Comment by edbaker83** [comment]
Created a pull request with the same change in for easier review.
https://github.com/OWASP/java-html-sanitizer/pull/78

Also the html spec https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-intable says:
```
When the user agent is to apply the rules for the "in table" insertion mode, the user agent must handle the token as follows:
...
A start tag whose tag name is one of: "style", "script", "template"
An end tag whose tag name is "template"
Process the token using the rules for the "in head" insertion mode.
```
So that allows "style" elements between "tr" elements.

**Comment by mikesamuel** [comment]
Thanks for digging up that spec reference.
