### ISSUE TITLE
'tr' tag is not closed as expected

### ISSUE THREAD

**Issue by andy-h-chen** [OWASP/java-html-sanitizer#80]
`<table><tbody><tr><td>td1</td><td>td2</tr><td>new line</tbody></table>`
is sanitised as
`<table><tbody><tr><td>td1</td><td>td2</td><td>new line</td></tr></tbody></table>`

Without addressing issue 77, it is supposed to close tbody and table before 'new line', but 'new line' is in the same row as 'td2'.

**Comment by mikesamuel** [comment]
https://github.com/OWASP/java-html-sanitizer/commit/00299d4c6c23bdeddd6aba5a2daa8defbe23299b
