### ISSUE TITLE
<br> vs <br />

### ISSUE THREAD

**Issue by virus006** [OWASP/java-html-sanitizer#85]
Hi all 

I am trying to sanitize a wysiwyg editor and noticed that the sanitizer uses the XHTML `<br />` tag. My front end sends the HTML `<br>` tag and can't get it to pass validation. I am using the following policy:

HtmlPolicyBuilder().allowCommonInlineFormattingElements().toFactory()  

Am i missing something or I have to convert the `<br>` tag to `<br />` before passing validation?

Thanks.

**Comment by mikesamuel** [comment]
`<br />` is perfectly valid HTML 5.

[HTML5's parsing algorithm](https://www.w3.org/TR/html5/syntax.html#tag-name-state) notes that a `/` after a tag name transitions to the self-closing start tag state, and when followed by a `>` causes the tag to close without emitting an error or warning.

HTML Sanitizer tries to put out HTML that is safe in as many contexts as possible so it tries to put out strings that mean the same thing to both HTML and XHTML parsers.

What validator are you using?  Does your document have a strict HTML4 doctype?

**Comment by virus006** [comment]
Ok, I understand now. Already took care of it.

Thank you very much.
