### ISSUE TITLE
why EbayPolicyExample escape + character

### ISSUE THREAD

**Issue by kmenzli** [OWASP/java-html-sanitizer#86]
I'm using the **EbayPolicyExample** on my own project, I noticed that character **+** has been escaped in output to **&#43** 
How can I change pattern in EbayPolicyExample to avoid escaping character **+**
Thanks

**Comment by kmenzli** [comment]
Any help is apreciated

**Comment by mikesamuel** [comment]
Based on discussions on the mailing list I believe this is invalid.  Please reopen if you have more detail.
