### ISSUE TITLE
Guava scope is causing issues in the latest release version

### ISSUE THREAD

**Issue by cartick** [OWASP/java-html-sanitizer#88]
We are using java-html-sanitizer in one of our libraries, and the version we specified is 
`[<version>, )`; so when we tried to deploy a war that was using our library (which was using java-html-sanitizer) we saw this error, 

**remote failure:** Error occurred during deployment: Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.NoClassDefFoundError: com/google/common/base/Function.

On further investigation we noticed that, 
com.google.guava : **guava** scope got changed to **provided** in latest version [**20160827.1**] of **java-html-sanitizer** ,  parent/pom.xml.

So our app was looking for the guava dependency to be provided by app server, since its not in our app server it failed to deploy. 

We tried building the library which was using the java-html-sanitizer, and we still had same issue, 
error: cannot access **Function**
but at compiler time, as guava dependencies scope is provided.

_What is the reason behind changing the scope to provided? 
Should we have to include the guava dependency in all of our app servers so they are providing the dependency to the application?_

**Comment by kevin-wise-infusionsoft** [comment]
This also affected us. I would also like an explanation of why the change was made.

**Comment by jmanico** [comment]
I ran into the same problem with the latest build (20160924.1). Adding Guava as a dependency fixed the problem, but I agree this came as a surprise and we'll work towards a code or documentation fix. Here is the Guava dependency:

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>19.0</version>
		</dependency>

@mikesamuel does this merit a fix, or should I change the docs to say we need to include Guava?

Aloha, jim

**Comment by mikesamuel** [comment]
I think the problem is the "fix" for https://github.com/OWASP/java-html-sanitizer/issues/67

Many Maven mavens recommends not using dependency ranges, and they have compelling arguments though they're not as convincing for projects like Guava that have a track record of handling backwards-compatibility well.

How about we remove the scope, and add a ranged dependency?

Any ideas on the dependency range we should use?

**Comment by cartick** [comment]
Its seems risky to have open ended version range, because if any of the dependency is not backwards compatible then that would break the build nd hence it would break all the dependent projects.
@mikesamuel and @jmanico , I think the below would be a good fix.
```
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>[11.0,20.0]</version>
      </dependency>
```
The guava comment in parent pom says we would need to start from 11.0 and the most recent guava version as of date, that is compatible with this project is 20.0. So this should work for now.

I created a pull request according to the above mentioned change #100 please review and provide your feedback.

And along with this change would it also be a good idea to change _open ended versioning_ to fixed range versioning on other dependencies?

**Comment by oyvindstegard** [comment]
We saw this as well and it's rather atypical compared to the other libs we include in the project. The requirement to declare an extra dependency on Guava if not already in your class path, should probably be documented here: https://github.com/OWASP/java-html-sanitizer/blob/master/docs/maven.md

**Comment by mariussoutier** [comment]
Wouldn't it be possible to replace Guava altogether with Java 8 features?

**Comment by jpetren** [comment]
please no.  i'm using this in some code that has to be compiled on java 7

**Comment by mikesamuel** [comment]
Java 7 will be supported for a while.  I've stopped manually running tests against Java 6 but Travis CI still does.

The pom.xml on master is what I plan for the next version.  IIRC I got rid of ranges.  I plan to update docs with a dependency with guava excluded example.

**Comment by TJEvans** [comment]
The minimum required version of Guava is now 14.0 based on the Jan 24th commit, https://github.com/OWASP/java-html-sanitizer/commit/13b37c0e92796e4c0b1f295ddbd3ff4921f559ed.  Resources.asByteSource was not introduced into Guava until 14.0.

**Comment by mikesamuel** [comment]
Thanks.  Will fix.

**Comment by cartick** [comment]
@mikesamuel thx for the fix.

For anyone who is using **Glassfish4.1.1** you might still have an issue, as the latest version of the project is using guava 19 and **Glassfish4.1.1** has an issue ([https://java.net/jira/browse/GLASSFISH-20850](https://java.net/jira/browse/GLASSFISH-20850)) which will use the guava classes from Glassfish provided version which is version-17.
So the fix for Glassfish4.1 user's will be to update guava.jar in **/glassfish/modules** with **guava 19** version

**Comment by mikesamuel** [comment]
Alternatively, for Glassfish4.1.1 compatibility, you can just depend on the sanitizer but exclude guava from its transitive closure which would leave the version of guava depended on by glassfish in the dependency set.

```xml
    <dependency>
      <groupId>com.googlecode.owasp-java-html-sanitizer</groupId>
      <artifactId>owasp-java-html-sanitizer</artifactId>
      <version>...</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
        </exclusion>
      </exclusions>
    <dependency>
```
