### ISSUE TITLE
Allow hyphens in font family name.

### ISSUE THREAD

**Issue by pukomuko** [OWASP/java-html-sanitizer#89]
This bug was already open a few times:
https://github.com/OWASP/java-html-sanitizer/issues/27
https://github.com/OWASP/java-html-sanitizer/issues/10

We need to specify fonts with their styles:
https://coderwall.com/p/gdpyjq/how-to-list-all-available-fonts-in-xcode-by-family-name

What steps will reproduce the problem?

```java
String css = "font-family:'ChalkboardSE-Light', 'Arial'";
StylingPolicy stylingPolicy = new StylingPolicy(CssSchema.DEFAULT);
stylingPolicy.sanitizeCssProperties(css);
```

What is the expected output? What do you see instead?
Expected: `font-family: 'chalkboardse-light' , 'arial'`
Actual: `font-family: , 'arial'`

There are two separate problems here:

1. Font names with hyphens are removed.
2. Comma is in incorrect place resulting in invalid css.

**Comment by mikesamuel** [comment]
PR was good after rerun.  Merged, added some tests.  Will release.
