### ISSUE TITLE
[feature request] Make public `unescapeHtml` method for decoding entities

### ISSUE THREAD

**Issue by grossws** [OWASP/java-html-sanitizer#91]
I use several policies to prepare data for indexing in Apache Lucene/Solr and some of them preserve html (with whitelisted tags and attrs) and one strips all tags. 

Since Solr does escaping by itself I want to get unescaped string in policy postprocessor (`org.owasp.html.HtmlStreamEventReceiverWrapper` subclass). Currently `org.owasp.html.Encoding` and its methods are package-private and I couldn't use `Encoding.unescapeHtml` there.

Of course, I can copy code from `Encoding` or add Apache Commons Lang to deps and use its `StringEscapeUtils.unescapeHtml` but it's incovenient to bring another lib to use one static method that OWASP sanitizer already has.

**Comment by mikesamuel** [comment]
Is `decodeHtml` the one you want?  There is no `unescapeHtml` in that class, though I haven't checked whether names have changed.

**Comment by grossws** [comment]
Sorry, it is actually called `Encoding.decodeHtml` in subject library. Method name `unescateHtml` was accidentaly brought from `commons-lang`'s `StringEscapeUtils` which I actually use now to workaround this issue.

**Comment by mikesamuel** [comment]
Will do

**Comment by mikesamuel** [comment]
https://github.com/OWASP/java-html-sanitizer/commit/c23c0172ad80b357baf825a91c4ded5550158f9c

**Comment by grossws** [comment]
Thanks, @mikesamuel

**Comment by sergeyk93** [comment]
Hi, @mikesamuel 
This fix doesn't work because the class is package private, so even though the method is public, it's impossible to access the class from outside the package.
