### ISSUE TITLE
"？" escaped to&#xff1f;

### ISSUE THREAD

**Issue by aftersss** [OWASP/java-html-sanitizer#92]
I am from china, when testing this project,I found that "？" will escape to "&#xff1f;", 
notice that "？" is a punctuation in Chinese.

test code is：
`PolicyFactory policyBuilder = new HtmlPolicyBuilder().allowElements("div")
                .toFactory();`
`String b = policyBuilder.sanitize("<div>1.Who am I？  2.Who are you?</div>");` 
`System.out.println(b);` 

output is:
`<div>1.Who am I&#xff1f;  2.Who are you?</div>`

**Comment by aftersss** [comment]
"！", "￥" will be escaped too, Can you fix it please

**Comment by mikesamuel** [comment]
How is this a problem?  The two seem to be equivalent HTML.

**Comment by LeoHuang2015** [comment]
> How is this a problem? The two seem to be equivalent HTML.

I think this is a problem, we see the process: 
User input: ，(Chinese comma).  --> santized and store in db: &#xff0c;   --> output to user:  html encode   output.    
In this case, the string will html encode twice!!!

**Comment by mikesamuel** [comment]
@LeoHuang2015 It sounds like your problem is that the code is encoding HTML retrieved from the database instead of sanitizing it.

**Comment by modefang** [comment]
@LeoHuang2015 有解决办法吗？

**Comment by nickfan** [comment]
@mikesamuel i think he would like to prevent the "？" character to encode into &#xff1f; ,
some characters like "？，：【】、「」——（）！￥……" in chinese is safe to store and show in raw format.
@modefang is that so? so reopen this issue,i don't have to open another one.

**Comment by mikesamuel** [comment]
@nickfan I understand that they would like that; I asked why they would like that.

That something is safe to store and show in raw format does not mean that adding a configuration option is worth the added complexity.

Nor does it mean that the project remains safe if testing and debugging effort is diluted by many configuration options.

**Comment by nickfan** [comment]
@mikesamuel for example:
if we use some WYSIWYG HTML editor something like CKEditor,to post html content and store in database,
use java-html-sanitizer to filter for security and show the filtered content in browser, so far so good
but when we load filtered content form db back to the WYSIWYG HTML editor, the characters like "？" and etc chinese characters are already encoded into ```&#xff1f;```,it will cause some WYSIWYG editor unable to restore the raw "？" character, or dubble encode the ```&#xff1f;``` into something like ```&amp;#xff1f;```,and became in a mess.

**Comment by mikesamuel** [comment]
@nickfan So your WYSIWYG HTML editor doesn't recognize HTML entities?

**Comment by nickfan** [comment]
http://ueditor.baidu.com/website/onlinedemo.html
hit the html ico in the bar to get into HTML mode, paste ```&#xff1f;``` hit again to switch back into WYSIWYG mode

![image](https://user-images.githubusercontent.com/100613/90267422-1a840680-de88-11ea-9985-8894a7df71ef.png)

it will dubble encode the ```&#xff1f;``` into ```&amp;#xff1f;```


in my actual situation:
i have to make my allowlist to convert the ```&#xff1f;``` and some other html entities back into characters, that i known is harmless and useful for next process,something like data Analysis and so on.

my point is : is there any way to prevent some unicode characters from been encoding into HTML entities? an allowlist maybe?
