### ISSUE TITLE
escape Unrecognized, or escape disallowed

### ISSUE THREAD

**Issue by xenoterracide** [OWASP/java-html-sanitizer#93]
given this
`<mg per week or  )` should return `&lt;mg per week or )`
`<E> Corp` should return `&lt;E&gt; Corp`

what we really need is a way to whitelist our formatting html, blacklist other known valid html but still allow crazy user inputs like the above because math and science are used in our software.

**Comment by mikesamuel** [comment]
> `<mg per week or )` should return `&lt;mg per week or )`

Isn't this what the sanitizer already does?

> `<E> Corp` should return `&lt;E&gt; Corp`

The sanitizer takes in HTML and produces HTML.
`<E> Corp` is an HTML tag, `<E>`, followed by some text " Corp".
An unrecognized tag is not equivalent to the text of that tag.
