### ISSUE TITLE
Allow specific CSS class?

### ISSUE THREAD

**Issue by owenconti** [OWASP/java-html-sanitizer#95]
Is there a way to white list class names on an element? Example:

```
.allowAttributes( "class" ).containing( true, "foo" ).onElements( "i" )
```

This would allow the 'foo' class on 'i' elements, but no other class name. I tried the following, but it strips the class entirely if it contains something other than the white listed values:

```
.allowAttributes( "class" ).matching( true, "foo" ).onElements( "i" )
```

So `<i class="foo bar"></i>` becomes: `<i></i>`, even though `<i class="foo"></i>` is valid.

**Comment by mikesamuel** [comment]
Yep.  The value matcher does not recognize that a class is a list of space separated items, so you could try defining a whitelist like

```java
public static final ImmutableSet<String> ALLOWED_CLASSES = ImmutableSet.of(
    "foo", "bar");
```

and then define your policy

 ```java
    .allowAttributes("class")
    .matching(
        (elementName, attributeName, value)
        -> Joiner.on(' ').join(
            Iterables.filter(
                Predicates.in(ALLOWED_CLASSES),
                Splitter.onPattern("\\s+").omitEmptyStrings().split(value))))
```
