### ISSUE TITLE
sanitizer encodes URL parameters 

### ISSUE THREAD

**Issue by agorski** [OWASP/java-html-sanitizer#98]
Sanitizer encodes URL parameters (e.g. equal and quotation signs)

Example:
`new HtmlPolicyBuilder()
                .allowElements("a", "p")
                .allowStandardUrlProtocols()
                .allowAttributes("href").onElements("a")
                .toFactory().sanitize("<a href=\"http://www.au.com?page=2&size=5\">text</a>")`

is sanitized/converted to:
`<a href="http://www.au.com?page&#61;2&amp;size&#61;5">text</a>`
but expected is:
`<a href="http://www.au.com?page=2&size=5">text</a>`

**Comment by agorski** [comment]
It was a misunderstanding of sanitizer functionality from my side.
Therefore ticket is closed.

**Comment by rbgarcia** [comment]
Hi, agorski.

I'm seeing the same behavior in my links and I have the same expectation you had when this issue was opened. Can you please shed some light on what was your misunderstanding and how can we produce valid links containing the equals (=) character?

Thank you.
