### ISSUE TITLE
Problem with inputs containing <

### ISSUE THREAD

**Issue by md384** [OWASP/java-html-sanitizer#99]
I am using the sanitizer with user input that might contain scientific notation and am having problems when the input contains `<`. The input is markdown-formatted text (which may contain HTML, hence using the sanitizer) so would rather not use `&lt;` and maintain readability.

As an example, the string `some x<z test` returns `some x` using the policy

```    
PolicyFactory policyFactory = new HtmlPolicyBuilder()
        .allowElements("div", "span")
        .allowWithoutAttributes("div", "span")
        .allowAttributes("class").onElements("div", "span")
        .allowStyling()
        .toFactory();
```

Using the same policy with the string `some x>z test` gives `some x&gt;z test` as expected.

**Comment by mikesamuel** [comment]
How is this a problem?

**Comment by md384** [comment]
Because `some x<z test` returns `some x` instead of `some x&lt;z text`.

**Comment by mikesamuel** [comment]
According to the w3 validator, the `<z` triggers

> Error: End of file occurred in an attribute name. 
> Ignoring tag.

so this seems correct behavior.
